### PR TITLE
Move base plots from LadybugTools_Toolkit

### LINKED ISSUE #141: Create general plot methods
#### Description:

From [LadybugTools_Toolkit](https://github.com/BHoM/LadybugTools_Toolkit), move methods for all base plot types (that don't require any more than numpy, matplotlib, pandas and other common libraries) to this toolkit, and in ladybugtools remove the old base plots and instead reference the new ones here.

Plot methods to be moved:
* diurnal
* heatmap
* histogram
* spatial_heatmap
* timeseries

This will also cover moving bhom_analytics to Python_Toolkit instead and calling it from everywhere else.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #141 

Moved all base plots that don't reference any pollination-based packages to Python_Toolkit, as well as helper and utility methods.

Also updated the .gitignore to align better with LBT_TK

### Test files

Use the unit tests in Python_Toolkit and LadybugTools_Toolkit, as there should be no change to method signatures or functionality in LBT (see the PR in LadybugTools_Toolkit)

### Changelog

* Moved the following base plots from LadybugTools_Toolkit:
    * diurnal
    * stacked_diurnals
    * heatmap
    * histogram
    * monthly_proportional_histogram
    * spatial_heatmap
    * timeseries
* Moved the following plot utility methods:
    * average_color
    * animation
    * create_title
    * contrasting_colour
    * relative_luminance
    * colormap_sequential
    * annotate_imshow
    * lighten_color
    * base64_to_image
    * image_to_base64
    * figure_to_base64
    * figure_to_image
    * tile_images
    * triangulation_area
    * create_triangulation
    * format_polar_plot
* Moved the following helper methods:
    * validate_timeseries
    * timeseries_summary_monthly
    * cardinality
    * angle_from_cardinal
    * angle_from_north
    * angle_to_vector
    * DecayMethod (enum for decay rate methods)
    * proximity_decay
    * decay_rate_smoother
    * sanitise_string
    * convert_keys_to_snake_case
    * remove_leap_days
    * timedelta_tostring
    * safe_filename

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
wrong PR 🤦

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by tg359 — APPROVED** [review]
Tests working on my machine, and no loss of functionality elsewhere (though there wouldn't be, if the elsewhere code isn't referencing it yet 😄).

There are lots of changes I'd love to make to how this toolkit is handling pots, but as with  most things, functionality over finesse is where we're at.

**Review by jamesramsden-bh — APPROVED** [review]
Tested with unit tests plus some self spot checks. No critical issues preventing merge. Any non-critical issues should have issues raised separately.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
