### PR TITLE
Removed Deprecated Methods

### LINKED ISSUE #110: Remove deprecated methods
Some methods have been marked with a todo to remove. Conversation with @tg359 confirmed that these can indeed be removed. 

Remove these methods by adding the appropriate attributes. If a method has been replaced, then delete the old method, and add this attribute to the replacement one, e.g. 

`[PreviousVersion("6.3","BH.Engine.Python.Compute.IsValidEnvironmentName(System.String)")]`

If the method is being removed without replacement, then we flag it for removal with the ToBeRemoved attribute, e.g. 

`[ToBeRemoved("6.3", "This method has been removed.")]`

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR
fixes #110 

### Test files
check that the deprecated methods are properly deleted

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check documentation-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
