### PR TITLE
Update to .NetStandard2.0

### LINKED ISSUE #119: Upgrade to .NetStandard2.0
This will be fun...

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #119

### CODE REVIEW

**Review by FelixMallinder-BH — APPROVED** [review]
Test and works successfully

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by Tom-Kingstone — APPROVED** [review]
Tested with current test procedure and works correctly.

**Review by albinber — APPROVED** [review]
Passed current test procedure

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
