### PR TITLE
Add python code to nuspec as content files

### LINKED ISSUE #146: Update nuspec file to include python library
#### Description:

similar to LadybugTools_Toolkit, will need to include the python files as content files:

```xml
<file src="C:\ProgramData\BHoM\Extensions\PythonCode\Python_Toolkit\src\python_toolkit\bhom\wrapped\**\*.*" exclude="**\__pycache__\*;**\docs\**\*" target="contentFiles\any\any\PythonCode\Python_Toolkit\src\python_toolkit\bhom\wrapped"/>
<file src="C:\ProgramData\BHoM\Extensions\PythonCode\Python_Toolkit\src\**\*.*" exclude="**\__pycache__\*;**\docs\**\*" target="contentFiles\any\any\PythonEnvironment\Lib\site-packages" />
```

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #146 

See the [nuspec file for LadybugTools_Toolkit](https://github.com/BHoM/LadybugTools_Toolkit/blob/develop/.ci/BHoMBot/Nuget/BHoM.Interop.LadybugTools.nuspec) as an example and compare to changes made here.
As python bhom analytics now exists in Python_Toolkit code, this must be included in the nuspec content files as well.
(not to mention future additions to Python_Toolkit python code)

### Test files

Likely will have to merge this then see if the bot produces nugets that contain the python files first

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Review by jamesramsden-bh — APPROVED** [review]
All fine

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Review by jamesramsden-bh — APPROVED** [review]
Happy with changes

**Comment by jamesramsden-bh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
