### PR TITLE
Enable Continuous Integration

### LINKED ISSUE #13: Enable Continuous Integration in this repo
#### Description:

Enable Continuous Integration in this repo usin Azure Pipelines

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #13 

### Additional comments

@FraserGreenroyd I have added the `.ci` files for to enable the continuous integration. Checked the latest commits you pushed for the MachineLearning_Toolkit as well. Would you mind setting up the Azure side of things when you have time?

### CODE REVIEW

**Comment by al-fisher** [comment]
Let me know if you want to make any of these _Required_

**Comment by epignatelli** [comment]
Thanks @FraserGreenroyd @al-fisher !
I made the CheckCore required for merging, as the toolkit moved to a more stable state!

**Pull request merged**
