### PR TITLE
Python_Toolkit: Fixed typos

### LINKED ISSUE #75: Fix some typos and spelling
#### Broken rules:
Some spelling errors/typos needs fixing. 

#### Suggestions to restore compliance:
CodeDirectory.cs Line 47: 
"This toolkits Python code doesn't seem to be installed."
should be "This toolkit's Python code doesn't seem to be installed."

InstallPythonEnvironment.cs Line 46:
"This component will install a Python environment for {pythonEnvironment.Name} if it doesn not exist, or return the eixtsing environment if it does."
should be "This component will install a Python environment for {pythonEnvironment.Name} if it doesn't exist, or return the existing environment if it does."

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #75 

Fixed requested typos

### CODE REVIEW

**Review by jamesramsden-bh — APPROVED** [review]
Typos fixed, ok by inspection. No code affected.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5990600669

**Pull request merged**
