### PR TITLE
Revert "Automatically install python if missing"

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Reverts BHoM/Python_Toolkit#41

I didn't see that the ML toolkit depended on it 🤦‍♂️

### CODE REVIEW

**Comment by al-fisher** [comment]
Hey @FraserGreenroyd - I actually think https://github.com/BHoM/MachineLearning_Toolkit/pull/50 is good to merge now anyway.

Messages back and forth with @BingWangUS and @epignatelli mean additional issues have been raised.

**Comment by FraserGreenroyd** [comment]
In that case will we be able to merge MachineLearning today @al-fisher ? I didn't realise the original Python was breaking changes in the other one 🤦‍♂️ so the installer currently won't build with master Python TK and master MachineLearning TK (sorry 😞 )

**Comment by al-fisher** [comment]
Yep - merging now! 😄

**Comment by al-fisher** [comment]
Done - was on my to-do-list for today anyway after Friday's chats. So no problem

**Comment by FraserGreenroyd** [comment]
Closing PR as MachineLearning is merged.

**Pull request closed without merging**
