### PR TITLE
Get a venv PythonEnvironment object from an environment name

### LINKED ISSUE #95: Get an environment object for a given environment name
It should be possible to query the location of a python.exe path for a virtual environment's name without the burden of calling the InstallVirtualenv method. 

This method will be very lightweight - it will only construct the path where python.exe should live, based upon an environment name, and will not attempt to install that environment. 

If the resultant path does not exist, an error should be returned to the user that the environment does not exist, and to run the appropriate env installer again.

### PR DESCRIPTION
**Pull request by jamesramsden-bh**
Closes #95 

A lightweight method to get a PythonEnvironment object for a virtual environment without the overheads of attempting to install said environment. 

Test by:
- Testing this PR against BHoM/LadybugTools_Toolkit#90 - in particular, whether the Materials and Typologies queries function correctly
- Running the Python TK test script

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyrght-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by tg359 — DISMISSED** [review]
Subject to changes to the copyright headers (after which I give it both thumbs up!), I've tested this and it works well to speed up the existing environment loading process.

**Comment by jamesramsden-bh** [comment]
@BHoMBot fix copyright headers ref. 11669880735

**Review by tg359 — APPROVED** [review]
I enjoy copyright headers that show the current year. I approve. For serious notes see my previous approval.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Pull request merged**
