### PR TITLE
Python virtual environment creation fixes and refactor

### LINKED ISSUE #106: requirements.txt not being generated correctly
In the interim-fixes branch, the requirements.txt does not get set up correctly. To fix, 
- remove the two erroneous lines half way down
- remove black
- remove versions for all packages other than LB/HB related packages. 

This is a priority fix as it prohibits the installation of the venv (without manually modifying the file anyway)

For reference, the following contents of requirements.txt result in a valid installation of the LB venv. 

aiofiles
aiohttp
aiosignal
aiosqlite
anyio
argon2-cffi
argon2-cffi-bindings
arrow
astroid
async-timeout
asynctest
attrs
Babel
backcall
beautifulsoup4
bleach
cached-property
case-converter
certifi
cffi
charset-normalizer
click
click-plugins
colorama
coverage
cramjam
cycler
debugpy
decorator
defusedxml
dill
distlib
dnspython
docutils
dragonfly-core==1.41.16
dragonfly-doe2==0.11.3
dragonfly-energy==1.23.23
dragonfly-radiance==0.2.54
dragonfly-schema==1.9.2
dragonfly-uwg==0.5.352
entrypoints
et-xmlfile
exceptiongroup
fastjsonschema
fastparquet
filelock
fonttools
fortranformat
fqdn
frozenlist
fsspec
greenlet
honeybee-core==1.55.15
honeybee-display==0.2.19
honeybee-energy==1.100.2
honeybee-energy-standards==2.2.6
honeybee-ies==0.7.1
honeybee-radiance==1.64.183
honeybee-radiance-command==1.22.2
honeybee-radiance-folder==2.11.11
honeybee-radiance-postprocess==0.4.219
honeybee-schema==1.53.2
honeybee-standards==2.0.6
honeybee-vtk==0.39.1
idna
importlib-metadata
importlib-resources
iniconfig
ipykernel
ipython
ipython-genutils
isoduration
isort
jedi
Jinja2
joblib
json5
jsonpointer
jsonschema
jupyter-events
jupyter-server
jupyter_client
jupyter_core
jupyter_server_fileid
jupyterlab
jupyterlab-pygments
jupyterlab_server
kiwisolver
ladybug-comfort==0.16.35
ladybug-core==0.41.25
ladybug-display==0.9.1
ladybug-geometry==1.27.1
ladybug-geometry-polyskel==1.4.18
ladybug-radiance==0.2.0
ladybug-rhino==1.39.14
lazy-object-proxy
lbt-dragonfly==0.10.146
lbt-honeybee==0.7.238
lbt-ladybug==0.27.24
lbt-recipes==0.25.8
lockfile
luigi
MarkupSafe
matplotlib
matplotlib-inline
mccabe
meteostat
mistune
multidict
mypy-extensions
nbclassic
nbclient
nbconvert
nbformat
nest-asyncio
notebook
notebook_shim
numexpr
numpy
opencv-python
openpyxl
packaging
pandas
pandas-downcast
pandocfilters
parso
pathspec
pickleshare
Pillow
pip-chill
pkgutil_resolve_name
platformdirs
pluggy
pollination-handlers==0.10.0
prometheus-client
prompt-toolkit
psutil
pyarrow
pycparser
pydantic
pydantic-openapi-helper
Pygments
pylint
pymongo
pyodbc
pyparsing
pyperclip
pyrsistent
pytest
pytest-cov
pytest-order
python-daemon
python-dateutil
python-json-logger
pytz
pywin32
pywinpty
PyYAML
pyzmq
queenbee==1.26.7
queenbee-local==0.5.4
requests
rfc3339-validator
rfc3986-validator
scikit-learn
scipy
Send2Trash
shapely
six
sniffio
sockets
soupsieve
SQLAlchemy
tables
tenacity
terminado
threadpoolctl
tinycss2
tomli
tomlkit
tornado
tqdm
traitlets
typed-ast
typing_extensions
uri-template
urllib3
uwg==5.8.11
virtualenv
vtk
wcwidth
webcolors
webencodings
websocket-client
wrapt
wslink
xlrd
y-py
yarl
ypy-websocket
zipp

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #106 

**As of 2023-08-03 this code certainly requires a bunch of versioning stuff added (as well as old code re-included) in order to appease the bot. This message will be removed once that's been done but I wanted to raise this now in WIP to stop me from forgetting.**

Changes should mean that reinstallation of an environment completely removes the old one in order to "start fresh" and avoid conflicts, plus methods of querying existing environments are a lot faster.

### CODE REVIEW

**Review by jamesramsden-bh — DISMISSED** [review]
Tested against successful installation and reinstallation of LBT TK

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot fix project file ref. 15713802954

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 15713802954

**Comment by jamesramsden-bh** [comment]
@BHoMBot check versioning

**Comment by jamesramsden-bh** [comment]
@BHoMBot check versioning

**Comment by jamesramsden-bh** [comment]
@BHoMBot check versioning

**Review by jamesramsden-bh — DISMISSED** [review]
Reconfirming approval after versioning fixes.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check code-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check code-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check code-compliance

**Review by jamesramsden-bh — APPROVED** [review]
Reapproving following folder name change for code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
