### PR TITLE
Add 3.7.2, enable formatting, register downstream environments in ipykernel

### LINKED ISSUE #79: Python_Toolkit: Add 3.7.2, enable formatting, register downstream environments in ipykernel
#### Description:

A range of additional tweaks to better set-up the BHoM Python environments.
- In order to allow Python 3.7.2 to be installed for a downstream toolkit to make use of this particular version of Python.
- Add "black" to default packages to enable formatting of BHoM Python code across any toolkits
- Register downstream environments with root environment ipykernel to enable access via Jupyter Notebooks
- Ensure environment-specific code is accessible in notebooks by prepending the `./PythonCode` directory to PATH in the base kernel upon creation.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #79 

Included Python 3.7.2 in list of installable versions. Also added [black](https://github.com/psf/black) to the list of default packages to include in the default installation.

### Test files

[79.zip](https://github.com/BHoM/Python_Toolkit/files/8529805/79.zip)

### CODE REVIEW

**Comment by tg359** [comment]
@BHoMBot check required

**Comment by tg359** [comment]
@BHoMBot check required

Not sure if my previous commit cancelled the original checks. Sorry if I anger you BHoMBot, please show mercy.

**Comment by tg359** [comment]
@BHoMBot check required

**Review by jamesramsden-bh — APPROVED** [review]
Changes don't appear to be breaking by inspection.

**Comment by tg359** [comment]
Closed due to other PR take precedence (#85)

**Pull request closed without merging**
